layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  hackerrank: cono_dipaola
  # instagram: your_username
  # keybase: your_username
  linkedin: conodipaola
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
   - name: CSS
     web_url: https://github.com/topics/css
     image_url: https://github.com/conodipaola/auxiliary_repo/blob/master/logos/css3.png

   - name: ReactJS
     web_url: https://github.com/topics/react
     image_url: https://github.com/conodipaola/auxiliary_repo/blob/master/logos/react.png

   - name: Javascript
     web_url: https://github.com/topics/javascript
     image_url: https://github.com/conodipaola/auxiliary_repo/blob/master/logos/javascript.png

   - name: HTML
     web_url: https://github.com/topics/html
     image_url: https://github.com/conodipaola/auxiliary_repo/blob/master/logos/html5.png

   - name: Unreal4
     web_url: https://github.com/topics/unreal-engine-4
     image_url: https://conodipaola.github.io/logos/unreal4.png

 #  - name: Sass
 #   web_url: https://github.com/topics/sass
 #   image_url: https://raw.githubusercontent.com/github/explore/6c6508f34230f0ac0d49e847a326429eefbfc030/topics/sass/sass.png
